import operator
from typing import Annotated, TypedDict, Union, List, Dict
import json
import os
import asyncio
import pandas as pd
import warnings
from dotenv import load_dotenv
from langgraph.graph import StateGraph, END
import jegal
from jegal.research_agents import NewsScannerAgent, FinancialResearchAgent, EarningsReviewerAgent
from jegal.engine_bridge import write_target_weights

# Suppress technical resource warnings (e.g. unclosed sockets from underlying SDKs)
# warnings.filterwarnings("ignore", category=ResourceWarning)
# warnings.filterwarnings("ignore", category=DeprecationWarning)
# warnings.filterwarnings("ignore", message="LangChainPendingDeprecationWarning")

# Load environment variables
load_dotenv()

# --- 1. Define State ---

class AgentState(TypedDict):
    # Sector configuration (from config.json)
    sectors: Dict[str, bool]
    # Tickers found by the News Scanner
    discovered_tickers: Annotated[List[str], operator.add]
    # Manual tickers from config
    manual_watchlist: List[str]
    # Current portfolio state from Rust broker
    portfolio_context: Dict[str, float]
    # Final target weights generated by researcher
    target_weights: Dict[str, List[Dict[str, Union[str, float]]]]
    # Full Markdown trade journal
    trade_journal: str

# --- 2. Define Agent Nodes ---

async def news_scanner_node(state: AgentState):
    print("\n[Node: News Scanner] Searching for catalysts...")
    scanner = NewsScannerAgent()
    active_sectors = [s for s, active in state["sectors"].items() if active]
    
    catalysts = await scanner.scan_for_catalysts(active_sectors)
    discovered = [item["ticker"] for item in catalysts]
    
    # Update config.json dynamic_watchlist for persistence (optional but good)
    with open("config.json", "r") as f:
        config = json.load(f)
    
    new_found = [t for t in discovered if t not in config["dynamic_watchlist"]]
    if new_found:
        config["dynamic_watchlist"].extend(new_found)
        with open("config.json", "w") as f:
            json.dump(config, f, indent=2)
    
    return {"discovered_tickers": discovered}

async def financial_researcher_node(state: AgentState):
    print("\n[Node: Financial Researcher] Performing deep analysis...")
    researcher = FinancialResearchAgent()
    earnings_agent = EarningsReviewerAgent()
    
    # Aggregate all tickers to research
    research_list = list(set(state["manual_watchlist"] + state["discovered_tickers"]))
    active_sectors = [s for s, active in state["sectors"].items() if active]
    
    # Perform core research
    journal, weights = await researcher.perform_market_research(
        symbols=research_list,
        active_sectors=active_sectors,
        current_portfolio=state["portfolio_context"]
    )
    
    # Add deep dives for top tickers
    for ticker in research_list[:2]:
        review = await earnings_agent.review_earnings(ticker)
        journal += f"\n\n### Deep Dive: {ticker}\n{review}"
    
    return {"target_weights": weights, "trade_journal": journal}

async def execution_node(state: AgentState):
    print("\n[Node: Execution] Handoff to Rust engine...")
    
    # Load Config for Risk and Broker settings
    with open("config.json", "r") as f:
        config = json.load(f)
    
    # 1. Save Journal
    os.makedirs("logs", exist_ok=True)
    with open("logs/research_report.md", "w") as f:
        f.write(state["trade_journal"])
    
    # 2. Dispatch Weights to Rust via Arrow IPC
    df = pd.DataFrame(state["target_weights"]["weights"])
    if df.empty:
        print("No target weights generated. Skipping execution.")
        return {}

    if 'ticker' in df.columns:
        df = df.rename(columns={'ticker': 'symbol'})
        
    ipc_path = "/tmp/jegal_target_weights.arrow"
    write_target_weights(df, ipc_path)
    
    # 3. Initialize Risk Manager from config
    risk_cfg = config["risk"]
    risk_manager = jegal.RiskManager(
        risk_cfg["max_exposure_per_symbol"],
        risk_cfg["max_total_exposure"],
        risk_cfg["drawdown_limit"],
        risk_cfg["max_orders_per_window"],
        risk_cfg["velocity_window_seconds"]
    )
    engine = jegal.ExecutionEngine(risk_manager)
    
    # 4. Connect to Broker from config
    broker_cfg = config["broker"]
    try:
        print(f"Connecting to {broker_cfg['type']} at {broker_cfg['host']}:{broker_cfg['port']}...")
        engine.set_broker(broker_cfg["type"], {
            "host": broker_cfg["host"],
            "port": broker_cfg["port"],
            "client_id": broker_cfg["client_id"]
        })
        print(f"Successfully connected to {broker_cfg['type']}!")
    except Exception as e:
        print(f"CRITICAL: Failed to connect to {broker_cfg['type']}: {e}")
        print("Falling back to MockBroker for simulation...")
        engine.set_broker("mock", {"balance": config["budget"]["total_budget"]})
        
    # 5. Run Rebalancing
    engine.run_rebalancing(ipc_path, tolerance=0.05)
    
    return {}

# --- 3. Build the Graph ---

def build_trading_graph():
    workflow = StateGraph(AgentState)
    
    # Add Nodes
    workflow.add_node("news_scanner", news_scanner_node)
    workflow.add_node("researcher", financial_researcher_node)
    workflow.add_node("execution", execution_node)
    
    # Define Edges (Clean Sequential Flow)
    workflow.set_entry_point("news_scanner")
    workflow.add_edge("news_scanner", "researcher")
    workflow.add_edge("researcher", "execution")
    workflow.add_edge("execution", END)
    
    return workflow.compile()

# --- 4. Main Execution ---

async def run_jegal():
    print("Jegal: Initializing LangGraph Autonomous Pipeline...")
    
    # Load Initial Config
    with open("config.json", "r") as f:
        config = json.load(f)
    
    # Initial State
    initial_state: AgentState = {
        "sectors": config["sectors"],
        "discovered_tickers": [],
        "manual_watchlist": config["manual_watchlist"],
        "portfolio_context": {}, # This could be fetched via a pre-node
        "target_weights": {"weights": []},
        "trade_journal": ""
    }
    
    app = build_trading_graph()
    
    # Execute the graph
    async for output in app.astream(initial_state):
        # Output is a dict with node name as key
        for key, value in output.items():
            print(f"--- Finished Node: {key} ---")

if __name__ == "__main__":
    asyncio.run(run_jegal())
